import Head from 'next/head'
import Header from '../components/Header'
import { useEffect ,useState,useContext} from 'react';
import dynamic from 'next/dynamic';
import IpContent from '../components/IpContent';
import { IpContext } from '../context/ipContext';



export default function Home() {
  // const [ip, setIp] = useState('8.8.8.8');
  const {ipData,setIpData,getIp} = useContext(IpContext);

useEffect(() => {
  // const fetchIp = async () => {
  //   const response = await fetch(`https://geo.ipify.org/api/v2/country,city?apiKey=at_obaZnNbeu8SgbcpG7H9dz9cQFqdmC&ipAddress=${ip}`);
  //   const jsonIp = await response.json();
  //   setIp(jsonIp);
  // }
  // fetchIp()
  getIp()
}, []);

  const MapContainers = dynamic(() => import('../components/MapContainers'),{
      ssr:false

  })

  return (
    <div >
      <Head>
        <title>Geo Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
        
      </Head>

      <main className='flex flex-col relative '>
        <Header />
        <IpContent/>
        <div id='map' className='mt-0'>
          <MapContainers />
        </div>
        
        </main>
    </div>
  )
}
